-- ---------------------------------------------------------------------
-- BMA-84: 이용권 구매/구독 결제
--   1. PY_PRODUCT 시드 (소모형 2종 + 구독 1종). 가격은 전부 임의치(공통컴포넌트 사양서 v1.7 CM-15/17).
--   2. PY_BILLING_KEY 신설 — 빌링키는 결제 1건이 아니라 사용자 1명에 귀속되어 매 청구마다 재사용한다.
--      토스 자동결제 승인에 필수인 customerKey 를 빌링키와 쌍으로 보관한다 (TOSS_SANDBOX_VERIFICATION.md 7절).
--   3. PY_SUBSCRIPTION 신설 — 구독 상태·청구 주기.
--   4. PY_USER_ITEM / PY_ITEM_LEDGER 신설 — 소모형 이용권 잔여 개수와 지급/사용 이력.
--      구독 지급분(GRANTED_QTY)과 구매분(PURCHASED_QTY)을 분리해 "이월 최대 2개월치" 상한을 지급분에만 건다.
--   5. PY_PAYMENT 에 결제 종류·구독 참조·결제 수단 추가.
--   6. MT_MATCH_QUEUE 에 진입 재원(무료/이용권/재매칭권) 기록 — 하루 무료 진입 횟수 계산용.
-- ---------------------------------------------------------------------

INSERT INTO `PY_PRODUCT` (`PRODUCT_CODE`, `PRODUCT_NAME`, `PRODUCT_TYPE`, `PRICE`, `CURRENCY_CODE`, `BENEFIT_JSON`, `USE_YN`, `INSERT_USER`)
VALUES
    ('MATCH_CHANCE',    '매칭기회 추가 1회', 'ITEM',         1000.00, 'KRW',
     '{"itemType":"MATCH_CHANCE","quantity":1}', 'Y', 'SYSTEM'),
    ('REMATCH_TICKET',  '재매칭권 1회',       'ITEM',         2000.00, 'KRW',
     '{"itemType":"REMATCH_TICKET","quantity":1}', 'Y', 'SYSTEM'),
    ('PREMIUM_MONTHLY', '정밀매칭 구독',      'SUBSCRIPTION', 9900.00, 'KRW',
     '{"periodMonths":1,"monthlyGrants":{"MATCH_CHANCE":3,"REMATCH_TICKET":2},"carryOverMonths":2,"precisionMatching":true,"revealWaitSkip":true}',
     'Y', 'SYSTEM');

CREATE TABLE `PY_BILLING_KEY` (
    `BILLING_KEY_ID` BIGINT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT '빌링키 ID',
    `USER_ID` BIGINT UNSIGNED NOT NULL COMMENT '사용자 ID',
    `CUSTOMER_KEY` VARCHAR(100) NOT NULL COMMENT '토스 customerKey (빌링키와 쌍)',
    `BILLING_KEY_ENC` VARBINARY(1000) NOT NULL COMMENT '빌링키 AES-GCM 암호문',
    `CARD_COMPANY` VARCHAR(50) NULL COMMENT '카드사',
    `CARD_NUMBER_MASKED` VARCHAR(30) NULL COMMENT '마스킹 카드번호',
    `KEY_STATUS` VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' COMMENT 'ACTIVE/REVOKED',
    `ISSUED_DATE` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '발급 일시',
    `REVOKED_DATE` DATETIME(6) NULL COMMENT '폐기 일시',
    `DELETED` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '논리 삭제 여부(Y/N)',
    `INSERT_USER` VARCHAR(50) NOT NULL COMMENT '최초 등록 사용자',
    `INSERT_DATE` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '최초 등록 일시',
    `UPDATE_USER` VARCHAR(50) NULL COMMENT '최종 수정 사용자',
    `UPDATE_DATE` DATETIME(6) NULL COMMENT '최종 수정 일시',
    `SYSTEM_REMARK` VARCHAR(1000) NULL COMMENT '시스템 처리 및 운영 메모',
    PRIMARY KEY (`BILLING_KEY_ID`),
    CONSTRAINT `UK_PY_BILLING_KEY_USER` UNIQUE (`USER_ID`),
    CONSTRAINT `UK_PY_BILLING_KEY_CUSTOMER` UNIQUE (`CUSTOMER_KEY`),
    CONSTRAINT `FK_PY_BILLING_KEY_USER_ID` FOREIGN KEY (`USER_ID`) REFERENCES `US_USER` (`USER_ID`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='사용자 단위 자동결제 빌링키';

CREATE TABLE `PY_SUBSCRIPTION` (
    `SUBSCRIPTION_ID` BIGINT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT '구독 ID',
    `USER_ID` BIGINT UNSIGNED NOT NULL COMMENT '사용자 ID',
    `PRODUCT_ID` BIGINT UNSIGNED NOT NULL COMMENT '구독 상품 ID',
    `BILLING_KEY_ID` BIGINT UNSIGNED NOT NULL COMMENT '청구에 쓰는 빌링키 ID',
    `SUB_STATUS` VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' COMMENT 'ACTIVE/PAST_DUE/CANCELED/EXPIRED',
    `STARTED_DATE` DATETIME(6) NOT NULL COMMENT '구독 시작 일시',
    `CURRENT_PERIOD_START` DATE NOT NULL COMMENT '현재 이용 기간 시작',
    `CURRENT_PERIOD_END` DATE NOT NULL COMMENT '현재 이용 기간 종료(이날까지 이용 가능)',
    `NEXT_BILLING_DATE` DATE NULL COMMENT '다음 청구일. 해지하면 NULL',
    `FAIL_COUNT` INT NOT NULL DEFAULT 0 COMMENT '연속 청구 실패 횟수',
    `LAST_PAYMENT_ID` BIGINT UNSIGNED NULL COMMENT '마지막 결제 ID',
    `CANCELED_DATE` DATETIME(6) NULL COMMENT '해지 요청 일시',
    `ENDED_DATE` DATETIME(6) NULL COMMENT '이용 종료 일시',
    `DELETED` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '논리 삭제 여부(Y/N)',
    `INSERT_USER` VARCHAR(50) NOT NULL COMMENT '최초 등록 사용자',
    `INSERT_DATE` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '최초 등록 일시',
    `UPDATE_USER` VARCHAR(50) NULL COMMENT '최종 수정 사용자',
    `UPDATE_DATE` DATETIME(6) NULL COMMENT '최종 수정 일시',
    `SYSTEM_REMARK` VARCHAR(1000) NULL COMMENT '시스템 처리 및 운영 메모',
    PRIMARY KEY (`SUBSCRIPTION_ID`),
    INDEX `IX_PY_SUBSCRIPTION_USER` (`USER_ID`, `SUB_STATUS`, `DELETED`),
    INDEX `IX_PY_SUBSCRIPTION_BILLING` (`SUB_STATUS`, `NEXT_BILLING_DATE`, `DELETED`),
    CONSTRAINT `FK_PY_SUBSCRIPTION_USER_ID` FOREIGN KEY (`USER_ID`) REFERENCES `US_USER` (`USER_ID`) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT `FK_PY_SUBSCRIPTION_PRODUCT_ID` FOREIGN KEY (`PRODUCT_ID`) REFERENCES `PY_PRODUCT` (`PRODUCT_ID`) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT `FK_PY_SUBSCRIPTION_BILLING_KEY_ID` FOREIGN KEY (`BILLING_KEY_ID`) REFERENCES `PY_BILLING_KEY` (`BILLING_KEY_ID`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='정밀매칭 구독';

CREATE TABLE `PY_USER_ITEM` (
    `USER_ITEM_ID` BIGINT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT '보유 이용권 ID',
    `USER_ID` BIGINT UNSIGNED NOT NULL COMMENT '사용자 ID',
    `ITEM_TYPE` VARCHAR(30) NOT NULL COMMENT 'MATCH_CHANCE/REMATCH_TICKET',
    `PURCHASED_QTY` INT NOT NULL DEFAULT 0 COMMENT '구매로 얻은 잔여 개수(소멸 없음)',
    `GRANTED_QTY` INT NOT NULL DEFAULT 0 COMMENT '구독 지급 잔여 개수(최대 2개월치까지만 누적)',
    `DELETED` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '논리 삭제 여부(Y/N)',
    `INSERT_USER` VARCHAR(50) NOT NULL COMMENT '최초 등록 사용자',
    `INSERT_DATE` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '최초 등록 일시',
    `UPDATE_USER` VARCHAR(50) NULL COMMENT '최종 수정 사용자',
    `UPDATE_DATE` DATETIME(6) NULL COMMENT '최종 수정 일시',
    `SYSTEM_REMARK` VARCHAR(1000) NULL COMMENT '시스템 처리 및 운영 메모',
    PRIMARY KEY (`USER_ITEM_ID`),
    CONSTRAINT `UK_PY_USER_ITEM` UNIQUE (`USER_ID`, `ITEM_TYPE`),
    CONSTRAINT `FK_PY_USER_ITEM_USER_ID` FOREIGN KEY (`USER_ID`) REFERENCES `US_USER` (`USER_ID`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='소모형 이용권 잔여 개수';

CREATE TABLE `PY_ITEM_LEDGER` (
    `LEDGER_ID` BIGINT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT '이력 ID',
    `USER_ID` BIGINT UNSIGNED NOT NULL COMMENT '사용자 ID',
    `ITEM_TYPE` VARCHAR(30) NOT NULL COMMENT 'MATCH_CHANCE/REMATCH_TICKET',
    `REASON_CODE` VARCHAR(30) NOT NULL COMMENT 'PURCHASE/GRANT/USE/EXPIRE',
    `DELTA_QTY` INT NOT NULL COMMENT '증감 수량(+지급/-사용·소멸)',
    `PURCHASED_AFTER` INT NOT NULL COMMENT '처리 후 구매분 잔여',
    `GRANTED_AFTER` INT NOT NULL COMMENT '처리 후 지급분 잔여',
    `REF_TYPE` VARCHAR(30) NULL COMMENT '참조 유형(PAYMENT/SUBSCRIPTION/MATCH_QUEUE/MATCH)',
    `REF_ID` BIGINT UNSIGNED NULL COMMENT '참조 ID',
    `GRANT_KEY` VARCHAR(100) NULL COMMENT '월 지급 멱등 키 {subscriptionId}:{yyyyMM}:{itemType}',
    `DELETED` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '논리 삭제 여부(Y/N)',
    `INSERT_USER` VARCHAR(50) NOT NULL COMMENT '최초 등록 사용자',
    `INSERT_DATE` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '최초 등록 일시',
    `UPDATE_USER` VARCHAR(50) NULL COMMENT '최종 수정 사용자',
    `UPDATE_DATE` DATETIME(6) NULL COMMENT '최종 수정 일시',
    `SYSTEM_REMARK` VARCHAR(1000) NULL COMMENT '시스템 처리 및 운영 메모',
    PRIMARY KEY (`LEDGER_ID`),
    CONSTRAINT `UK_PY_ITEM_LEDGER_GRANT` UNIQUE (`GRANT_KEY`),
    INDEX `IX_PY_ITEM_LEDGER_USER` (`USER_ID`, `ITEM_TYPE`, `INSERT_DATE`),
    CONSTRAINT `FK_PY_ITEM_LEDGER_USER_ID` FOREIGN KEY (`USER_ID`) REFERENCES `US_USER` (`USER_ID`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='이용권 지급/사용 이력';

ALTER TABLE `PY_PAYMENT`
    ADD COLUMN `PAYMENT_KIND` VARCHAR(20) NOT NULL DEFAULT 'CONSUMABLE' COMMENT 'CONSUMABLE/SUBSCRIPTION' AFTER `PRODUCT_ID`,
    ADD COLUMN `PAY_METHOD` VARCHAR(20) NULL COMMENT 'WIDGET(결제창 승인)/BILLING(빌링키 자동결제)' AFTER `PAYMENT_KIND`,
    ADD COLUMN `ORDER_NAME` VARCHAR(200) NULL COMMENT '주문명' AFTER `ORDER_ID`,
    ADD COLUMN `SUBSCRIPTION_ID` BIGINT UNSIGNED NULL COMMENT '구독 청구인 경우 구독 ID' AFTER `PAYMENT_KEY`,
    ADD INDEX `IX_PY_PAYMENT_SUBSCRIPTION` (`SUBSCRIPTION_ID`, `INSERT_DATE`);

ALTER TABLE `MT_MATCH_QUEUE`
    ADD COLUMN `ENTRY_SOURCE` VARCHAR(20) NOT NULL DEFAULT 'FREE' COMMENT '진입 재원 FREE(무료 일일 기회)/ITEM(매칭기회 이용권)/REMATCH(재매칭권)' AFTER `QUEUE_STATUS`,
    ADD INDEX `IX_MT_QUEUE_USER_ENTER` (`USER_ID`, `ENTER_DATE`, `DELETED`);
