-- ---------------------------------------------------------------------
-- BMA-76: S12 관리자 신고검토 — 감사 로그(BMA-30 "모든 조치는 누가/언제/무슨 근거/무슨 조치로 기록") (2026-09-23)
--   1. SF_ADMIN_AUDIT_LOG 신설. 신고 승인/반려, 제재 부과/해제, 대화 종료를 관리자 ID 와 함께 남긴다.
--      BMA-14 에서 "감사로그 컬럼 추가 필요"로 남아 있던 항목. 기존 SF_USER_REPORT 의 PROCESS_USER_ID/PROCESS_DATE/ACTION_CODE 는
--      신고 1건의 최종 결과이고, 감사 로그는 그 과정의 모든 행위를 시간순으로 보관한다(S12-08 감사 로그 표시).
--   2. SF_USER_REPORT.REVIEW_NOTE — 관리자 검토 메모.
-- ---------------------------------------------------------------------
CREATE TABLE `SF_ADMIN_AUDIT_LOG` (
    `AUDIT_ID` BIGINT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT '감사 로그 ID',
    `ADMIN_USER_ID` BIGINT UNSIGNED NOT NULL COMMENT '행위 관리자',
    `ACTION_CODE` VARCHAR(30) NOT NULL COMMENT 'REPORT_APPROVE/REPORT_REJECT/SANCTION_WARNING/SANCTION_SUSPEND/SANCTION_BAN/SANCTION_LIFT/CONVERSATION_END',
    `TARGET_USER_ID` BIGINT UNSIGNED NULL COMMENT '조치 대상 사용자',
    `REPORT_ID` BIGINT UNSIGNED NULL COMMENT '근거 신고',
    `SANCTION_ID` BIGINT UNSIGNED NULL COMMENT '부과/해제된 제재',
    `DETAIL` VARCHAR(1000) NULL COMMENT '근거·메모(누적 횟수, 사유 등)',
    `ACTION_DATE` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '행위 일시',
    `DELETED` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '논리 삭제 여부(Y/N)',
    `INSERT_USER` VARCHAR(50) NOT NULL COMMENT '최초 등록 사용자',
    `INSERT_DATE` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '최초 등록 일시',
    `UPDATE_USER` VARCHAR(50) NULL COMMENT '최종 수정 사용자',
    `UPDATE_DATE` DATETIME(6) NULL COMMENT '최종 수정 일시',
    `SYSTEM_REMARK` VARCHAR(1000) NULL COMMENT '시스템 처리 및 운영 메모',
    PRIMARY KEY (`AUDIT_ID`),
    INDEX `IX_SF_AUDIT_TARGET` (`TARGET_USER_ID`, `ACTION_DATE`),
    INDEX `IX_SF_AUDIT_REPORT` (`REPORT_ID`),
    INDEX `IX_SF_AUDIT_DATE` (`ACTION_DATE`),
    CONSTRAINT `FK_SF_ADMIN_AUDIT_LOG_ADMIN_USER_ID` FOREIGN KEY (`ADMIN_USER_ID`) REFERENCES `US_USER` (`USER_ID`) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT `FK_SF_ADMIN_AUDIT_LOG_TARGET_USER_ID` FOREIGN KEY (`TARGET_USER_ID`) REFERENCES `US_USER` (`USER_ID`) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT `FK_SF_ADMIN_AUDIT_LOG_REPORT_ID` FOREIGN KEY (`REPORT_ID`) REFERENCES `SF_USER_REPORT` (`REPORT_ID`) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT `FK_SF_ADMIN_AUDIT_LOG_SANCTION_ID` FOREIGN KEY (`SANCTION_ID`) REFERENCES `SF_USER_SANCTION` (`SANCTION_ID`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='관리자 조치 감사 로그';

ALTER TABLE `SF_USER_REPORT`
    ADD COLUMN `REVIEW_NOTE` VARCHAR(1000) NULL COMMENT '관리자 검토 메모' AFTER `PROCESS_DATE`,
    MODIFY COLUMN `ACTION_CODE` VARCHAR(30) NULL COMMENT '승인 시 실행한 조치: NONE/WARNING/SUSPEND/BAN';
