-- ---------------------------------------------------------------------
-- BMA-79: S15 본인인증 (BMA-31 MVP 필수 관문, BMA-19 안건3 미성년자 가입 불가) (2026-09-24)
--   1. US_USER 에 본인인증 상태 컬럼 추가(BMA-14 스키마 반영). 인증사가 돌려준 CI 는 해시로만 보관해
--      한 사람이 여러 계정을 만드는 것을 막고, 검증된 생년월일은 성인 판정 근거로 남긴다.
--   2. US_IDENTITY_VERIFICATION 신설 — 인증 요청(거래 ID·만료)과 결과(성공/미성년자 거부/중복/실패)를 시도 단위로 기록.
--      실명·전화번호는 마스킹해 저장하고 원문은 남기지 않는다.
-- ---------------------------------------------------------------------
ALTER TABLE `US_USER`
    ADD COLUMN `IDENTITY_VERIFIED_YN` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '본인인증 완료 여부(Y/N)' AFTER `PHONE_VERIFIED_YN`,
    ADD COLUMN `IDENTITY_VERIFIED_DATE` DATETIME(6) NULL COMMENT '본인인증 완료 일시' AFTER `IDENTITY_VERIFIED_YN`,
    ADD COLUMN `IDENTITY_PROVIDER` VARCHAR(20) NULL COMMENT '인증사(stub/pass/nice/toss 등)' AFTER `IDENTITY_VERIFIED_DATE`,
    ADD COLUMN `IDENTITY_CI_HASH` VARCHAR(64) NULL COMMENT '인증사 CI 의 SHA-256 (중복 계정 방지)' AFTER `IDENTITY_PROVIDER`,
    ADD COLUMN `IDENTITY_BIRTH_DATE` DATE NULL COMMENT '인증사가 검증한 생년월일(성인 판정 근거)' AFTER `IDENTITY_CI_HASH`,
    ADD INDEX `IX_US_USER_IDENTITY_CI` (`IDENTITY_CI_HASH`, `DELETED`);

CREATE TABLE `US_IDENTITY_VERIFICATION` (
    `VERIFICATION_ID` BIGINT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT '인증 시도 ID',
    `USER_ID` BIGINT UNSIGNED NOT NULL COMMENT '요청 사용자',
    `TRANSACTION_ID` VARCHAR(64) NOT NULL COMMENT '거래 ID(SDK 호출·결과 확인에 쓰는 키)',
    `PROVIDER` VARCHAR(20) NOT NULL COMMENT '인증사',
    `STATUS` VARCHAR(20) NOT NULL DEFAULT 'REQUESTED' COMMENT 'REQUESTED/VERIFIED/REJECTED_MINOR/REJECTED_DUPLICATE/FAILED/EXPIRED',
    `EXPIRE_DATE` DATETIME(6) NOT NULL COMMENT '요청 만료 일시',
    `CONFIRM_DATE` DATETIME(6) NULL COMMENT '결과 확인 일시',
    `RESULT_NAME_MASKED` VARCHAR(50) NULL COMMENT '인증 결과 이름(마스킹)',
    `RESULT_BIRTH_DATE` DATE NULL COMMENT '인증 결과 생년월일',
    `RESULT_GENDER_CODE` CHAR(1) NULL COMMENT '인증 결과 성별(M/F)',
    `RESULT_PHONE_MASKED` VARCHAR(30) NULL COMMENT '인증 결과 전화번호(마스킹)',
    `FAIL_REASON` VARCHAR(500) NULL COMMENT '실패·거부 사유',
    `DELETED` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '논리 삭제 여부(Y/N)',
    `INSERT_USER` VARCHAR(50) NOT NULL COMMENT '최초 등록 사용자',
    `INSERT_DATE` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '최초 등록 일시',
    `UPDATE_USER` VARCHAR(50) NULL COMMENT '최종 수정 사용자',
    `UPDATE_DATE` DATETIME(6) NULL COMMENT '최종 수정 일시',
    `SYSTEM_REMARK` VARCHAR(1000) NULL COMMENT '시스템 처리 및 운영 메모',
    PRIMARY KEY (`VERIFICATION_ID`),
    UNIQUE KEY `UK_US_IDENTITY_VERIFICATION_TX` (`TRANSACTION_ID`),
    INDEX `IX_US_IDENTITY_VERIFICATION_USER` (`USER_ID`, `STATUS`, `DELETED`),
    CONSTRAINT `FK_US_IDENTITY_VERIFICATION_USER_ID` FOREIGN KEY (`USER_ID`) REFERENCES `US_USER` (`USER_ID`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='본인인증 요청·결과 이력';
