-- ---------------------------------------------------------------------
-- BMA-82: S16 사진인증 (BMA-31 선택 기능, S7-11 미인증 상대 알림) (2026-09-24)
--   1. US_USER 에 사진인증 상태 컬럼 추가(BMA-14 스키마 반영). 어떤 프로필 사진으로 인증했는지(PHOTO_VERIFIED_IMAGE_ID)를 남겨
--      사진을 바꾸면 배지가 자동으로 내려가게 한다.
--   2. US_PHOTO_VERIFICATION 신설 — 시도 단위 기록(결과·유사도·임계값). 촬영한 셀피는 어디에도 저장하지 않는다(개인정보).
-- ---------------------------------------------------------------------
ALTER TABLE `US_USER`
    ADD COLUMN `PHOTO_VERIFIED_YN` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '사진인증 완료 여부(Y/N) — S5/S10 배지' AFTER `IDENTITY_BIRTH_DATE`,
    ADD COLUMN `PHOTO_VERIFIED_DATE` DATETIME(6) NULL COMMENT '사진인증 완료 일시' AFTER `PHOTO_VERIFIED_YN`,
    ADD COLUMN `PHOTO_VERIFY_PROVIDER` VARCHAR(20) NULL COMMENT '얼굴 대조 제공자(stub/rekognition 등)' AFTER `PHOTO_VERIFIED_DATE`,
    ADD COLUMN `PHOTO_VERIFIED_IMAGE_ID` BIGINT UNSIGNED NULL COMMENT '인증 당시 대조한 프로필 사진(바뀌면 인증 해제)' AFTER `PHOTO_VERIFY_PROVIDER`;

CREATE TABLE `US_PHOTO_VERIFICATION` (
    `PHOTO_VERIFICATION_ID` BIGINT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT '시도 ID',
    `USER_ID` BIGINT UNSIGNED NOT NULL COMMENT '사용자',
    `PROVIDER` VARCHAR(20) NOT NULL COMMENT '얼굴 대조 제공자',
    `RESULT` VARCHAR(20) NOT NULL COMMENT 'PASS/FAIL/ERROR',
    `SIMILARITY` DECIMAL(5,2) NULL COMMENT '유사도(0~100)',
    `THRESHOLD` DECIMAL(5,2) NOT NULL COMMENT '통과 기준',
    `PROFILE_IMAGE_ID` BIGINT UNSIGNED NULL COMMENT '대조한 프로필 사진',
    `FAIL_REASON` VARCHAR(500) NULL COMMENT '실패·오류 사유',
    `DELETED` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '논리 삭제 여부(Y/N)',
    `INSERT_USER` VARCHAR(50) NOT NULL COMMENT '최초 등록 사용자',
    `INSERT_DATE` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '최초 등록 일시',
    `UPDATE_USER` VARCHAR(50) NULL COMMENT '최종 수정 사용자',
    `UPDATE_DATE` DATETIME(6) NULL COMMENT '최종 수정 일시',
    `SYSTEM_REMARK` VARCHAR(1000) NULL COMMENT '시스템 처리 및 운영 메모',
    PRIMARY KEY (`PHOTO_VERIFICATION_ID`),
    INDEX `IX_US_PHOTO_VERIFICATION_USER` (`USER_ID`, `INSERT_DATE`),
    CONSTRAINT `FK_US_PHOTO_VERIFICATION_USER_ID` FOREIGN KEY (`USER_ID`) REFERENCES `US_USER` (`USER_ID`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='사진인증 시도 이력(셀피 미저장)';
