-- =====================================================================
-- V1: 초기 스키마 (업무 테이블 32개)
--
-- BMA-14 에서 설계한 BMA_MYSQL_SCHEMA_V1_0.sql 을 Flyway 마이그레이션으로 옮긴 것이다.
-- 원본과 달라진 점:
--   - CREATE DATABASE / USE 제거: 대상 스키마는 접속 URL 이 결정한다.
--     마이그레이션이 DB 이름을 하드코딩하면 테스트/운영 스키마에서 재사용할 수 없다.
--   - DROP TABLE IF EXISTS 제거: V1 은 빈 스키마에만 적용되므로 불필요하고,
--     혹시라도 재실행되면 운영 데이터를 지우는 사고로 이어진다.
--   - 공통 코드 시드 데이터는 V2 로 분리했다.
-- =====================================================================
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;


-- ---------------------------------------------------------------------
-- CM_CODE_GROUP: 공통 코드 그룹
-- ---------------------------------------------------------------------
CREATE TABLE `CM_CODE_GROUP` (
    `CODE_GROUP` VARCHAR(50) NOT NULL COMMENT '코드 그룹',
    `CODE_GROUP_NAME` VARCHAR(100) NOT NULL COMMENT '코드 그룹명',
    `DESCRIPTION` VARCHAR(500) NULL COMMENT '설명',
    `USE_YN` CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '사용 여부',
    `DELETED` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '논리 삭제 여부(Y/N)',
    `INSERT_USER` VARCHAR(50) NOT NULL COMMENT '최초 등록 사용자',
    `INSERT_DATE` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '최초 등록 일시',
    `UPDATE_USER` VARCHAR(50) NULL COMMENT '최종 수정 사용자',
    `UPDATE_DATE` DATETIME(6) NULL COMMENT '최종 수정 일시',
    `SYSTEM_REMARK` VARCHAR(1000) NULL COMMENT '시스템 처리 및 운영 메모',
    PRIMARY KEY (`CODE_GROUP`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='공통 코드 그룹';

-- ---------------------------------------------------------------------
-- CM_CODE: 공통 코드 상세
-- ---------------------------------------------------------------------
CREATE TABLE `CM_CODE` (
    `CODE_GROUP` VARCHAR(50) NOT NULL COMMENT '코드 그룹',
    `CODE` VARCHAR(50) NOT NULL COMMENT '코드',
    `CODE_NAME` VARCHAR(100) NOT NULL COMMENT '코드명',
    `CODE_VALUE` VARCHAR(500) NULL COMMENT '추가 코드 값',
    `SORT_ORDER` INT NOT NULL DEFAULT 0 COMMENT '정렬 순서',
    `USE_YN` CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '사용 여부',
    `DELETED` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '논리 삭제 여부(Y/N)',
    `INSERT_USER` VARCHAR(50) NOT NULL COMMENT '최초 등록 사용자',
    `INSERT_DATE` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '최초 등록 일시',
    `UPDATE_USER` VARCHAR(50) NULL COMMENT '최종 수정 사용자',
    `UPDATE_DATE` DATETIME(6) NULL COMMENT '최종 수정 일시',
    `SYSTEM_REMARK` VARCHAR(1000) NULL COMMENT '시스템 처리 및 운영 메모',
    PRIMARY KEY (`CODE_GROUP`, `CODE`),
    CONSTRAINT `FK_CM_CODE_CODE_GROUP` FOREIGN KEY (`CODE_GROUP`) REFERENCES `CM_CODE_GROUP` (`CODE_GROUP`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='공통 코드 상세';

-- ---------------------------------------------------------------------
-- US_USER: 로그인 계정 및 서비스 상태
-- ---------------------------------------------------------------------
CREATE TABLE `US_USER` (
    `USER_ID` BIGINT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT '사용자 ID',
    `EMAIL` VARCHAR(255) NOT NULL COMMENT '로그인 이메일',
    `PASSWORD_HASH` VARCHAR(255) NULL COMMENT '암호화 비밀번호; 소셜 가입은 NULL 가능',
    `PHONE_NUMBER` VARCHAR(30) NULL COMMENT '휴대전화 번호',
    `LOGIN_PROVIDER` VARCHAR(20) NOT NULL DEFAULT 'LOCAL' COMMENT 'LOCAL/KAKAO/GOOGLE/NAVER/APPLE',
    `PROVIDER_USER_KEY` VARCHAR(255) NULL COMMENT '소셜 제공자 사용자 키',
    `USER_ROLE` VARCHAR(20) NOT NULL DEFAULT 'USER' COMMENT 'USER/ADMIN',
    `USER_STATUS` VARCHAR(20) NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING/ACTIVE/SUSPENDED/WITHDRAWN',
    `EMAIL_VERIFIED_YN` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '이메일 인증 여부',
    `PHONE_VERIFIED_YN` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '휴대전화 인증 여부',
    `LAST_LOGIN_DATE` DATETIME(6) NULL COMMENT '마지막 로그인 일시',
    `SUSPENDED_UNTIL` DATETIME(6) NULL COMMENT '정지 종료 예정 일시',
    `WITHDRAW_DATE` DATETIME(6) NULL COMMENT '탈퇴 일시',
    `DELETED` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '논리 삭제 여부(Y/N)',
    `INSERT_USER` VARCHAR(50) NOT NULL COMMENT '최초 등록 사용자',
    `INSERT_DATE` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '최초 등록 일시',
    `UPDATE_USER` VARCHAR(50) NULL COMMENT '최종 수정 사용자',
    `UPDATE_DATE` DATETIME(6) NULL COMMENT '최종 수정 일시',
    `SYSTEM_REMARK` VARCHAR(1000) NULL COMMENT '시스템 처리 및 운영 메모',
    PRIMARY KEY (`USER_ID`),
    CONSTRAINT `UK_US_USER_EMAIL` UNIQUE (`EMAIL`),
    CONSTRAINT `UK_US_USER_PHONE` UNIQUE (`PHONE_NUMBER`),
    CONSTRAINT `UK_US_USER_PROVIDER` UNIQUE (`LOGIN_PROVIDER`, `PROVIDER_USER_KEY`),
    INDEX `IX_US_USER_STATUS` (`USER_STATUS`, `DELETED`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='로그인 계정 및 서비스 상태';

-- ---------------------------------------------------------------------
-- US_USER_TOKEN: 리프레시 토큰 및 인증 토큰
-- ---------------------------------------------------------------------
CREATE TABLE `US_USER_TOKEN` (
    `TOKEN_ID` BIGINT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT '토큰 ID',
    `USER_ID` BIGINT UNSIGNED NOT NULL COMMENT '사용자 ID',
    `TOKEN_TYPE` VARCHAR(30) NOT NULL COMMENT 'REFRESH/EMAIL_VERIFY/PASSWORD_RESET',
    `TOKEN_HASH` VARCHAR(255) NOT NULL COMMENT '원문 대신 해시 저장',
    `EXPIRE_DATE` DATETIME(6) NOT NULL COMMENT '만료 일시',
    `USED_DATE` DATETIME(6) NULL COMMENT '사용 완료 일시',
    `DELETED` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '논리 삭제 여부(Y/N)',
    `INSERT_USER` VARCHAR(50) NOT NULL COMMENT '최초 등록 사용자',
    `INSERT_DATE` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '최초 등록 일시',
    `UPDATE_USER` VARCHAR(50) NULL COMMENT '최종 수정 사용자',
    `UPDATE_DATE` DATETIME(6) NULL COMMENT '최종 수정 일시',
    `SYSTEM_REMARK` VARCHAR(1000) NULL COMMENT '시스템 처리 및 운영 메모',
    PRIMARY KEY (`TOKEN_ID`),
    CONSTRAINT `UK_US_USER_TOKEN_HASH` UNIQUE (`TOKEN_HASH`),
    INDEX `IX_US_USER_TOKEN_USER` (`USER_ID`, `TOKEN_TYPE`, `DELETED`),
    CONSTRAINT `FK_US_USER_TOKEN_USER_ID` FOREIGN KEY (`USER_ID`) REFERENCES `US_USER` (`USER_ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='리프레시 토큰 및 인증 토큰';

-- ---------------------------------------------------------------------
-- US_USER_PROFILE: 매칭에 사용하는 사용자 프로필
-- ---------------------------------------------------------------------
CREATE TABLE `US_USER_PROFILE` (
    `USER_ID` BIGINT UNSIGNED NOT NULL COMMENT '사용자 ID',
    `NICKNAME` VARCHAR(50) NOT NULL COMMENT '서비스 표시 닉네임',
    `REAL_NAME_ENC` VARBINARY(500) NULL COMMENT '실명 암호화 값',
    `BIRTH_DATE` DATE NOT NULL COMMENT '생년월일',
    `GENDER_CODE` VARCHAR(20) NOT NULL COMMENT '성별 코드',
    `MBTI_CODE` VARCHAR(4) NULL COMMENT 'MBTI',
    `REGION_CODE` VARCHAR(20) NULL COMMENT '활동 지역 코드',
    `OCCUPATION` VARCHAR(100) NULL COMMENT '직업',
    `COMPANY_CATEGORY` VARCHAR(100) NULL COMMENT '회사/업종 분류',
    `EDUCATION_CODE` VARCHAR(30) NULL COMMENT '학력 코드',
    `HEIGHT_CM` SMALLINT UNSIGNED NULL COMMENT '키(cm)',
    `RELIGION_CODE` VARCHAR(30) NULL COMMENT '종교 코드',
    `DRINKING_CODE` VARCHAR(20) NULL COMMENT '음주 코드',
    `SMOKING_CODE` VARCHAR(20) NULL COMMENT '흡연 코드',
    `INTRODUCTION` VARCHAR(1000) NULL COMMENT '자기소개',
    `PROFILE_STATUS` VARCHAR(20) NOT NULL DEFAULT 'INCOMPLETE' COMMENT 'INCOMPLETE/REVIEW/COMPLETE/REJECTED',
    `PROFILE_SCORE` INT NOT NULL DEFAULT 0 COMMENT '프로필 완성도',
    `LAST_ACTIVE_DATE` DATETIME(6) NULL COMMENT '마지막 활동 일시',
    `DELETED` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '논리 삭제 여부(Y/N)',
    `INSERT_USER` VARCHAR(50) NOT NULL COMMENT '최초 등록 사용자',
    `INSERT_DATE` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '최초 등록 일시',
    `UPDATE_USER` VARCHAR(50) NULL COMMENT '최종 수정 사용자',
    `UPDATE_DATE` DATETIME(6) NULL COMMENT '최종 수정 일시',
    `SYSTEM_REMARK` VARCHAR(1000) NULL COMMENT '시스템 처리 및 운영 메모',
    PRIMARY KEY (`USER_ID`),
    CONSTRAINT `UK_US_USER_PROFILE_NICKNAME` UNIQUE (`NICKNAME`),
    INDEX `IX_US_PROFILE_MATCHING` (`GENDER_CODE`, `REGION_CODE`, `PROFILE_STATUS`, `DELETED`),
    CONSTRAINT `FK_US_USER_PROFILE_USER_ID` FOREIGN KEY (`USER_ID`) REFERENCES `US_USER` (`USER_ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='매칭에 사용하는 사용자 프로필';

-- ---------------------------------------------------------------------
-- US_PROFILE_IMAGE: 프로필 이미지 및 블라인드 표시 정보
-- ---------------------------------------------------------------------
CREATE TABLE `US_PROFILE_IMAGE` (
    `IMAGE_ID` BIGINT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT '이미지 ID',
    `USER_ID` BIGINT UNSIGNED NOT NULL COMMENT '사용자 ID',
    `ORIGINAL_URL` VARCHAR(1000) NOT NULL COMMENT '원본 이미지 URL',
    `BLURRED_URL` VARCHAR(1000) NULL COMMENT '블러 처리 이미지 URL',
    `SILHOUETTE_URL` VARCHAR(1000) NULL COMMENT '실루엣 이미지 URL',
    `IMAGE_TYPE` VARCHAR(20) NOT NULL DEFAULT 'PROFILE' COMMENT 'PROFILE/VERIFICATION',
    `DISPLAY_ORDER` INT NOT NULL DEFAULT 1 COMMENT '표시 순서',
    `PRIMARY_YN` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '대표 이미지 여부',
    `REVIEW_STATUS` VARCHAR(20) NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING/APPROVED/REJECTED',
    `DELETED` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '논리 삭제 여부(Y/N)',
    `INSERT_USER` VARCHAR(50) NOT NULL COMMENT '최초 등록 사용자',
    `INSERT_DATE` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '최초 등록 일시',
    `UPDATE_USER` VARCHAR(50) NULL COMMENT '최종 수정 사용자',
    `UPDATE_DATE` DATETIME(6) NULL COMMENT '최종 수정 일시',
    `SYSTEM_REMARK` VARCHAR(1000) NULL COMMENT '시스템 처리 및 운영 메모',
    PRIMARY KEY (`IMAGE_ID`),
    INDEX `IX_US_PROFILE_IMAGE_USER` (`USER_ID`, `DELETED`, `DISPLAY_ORDER`),
    CONSTRAINT `FK_US_PROFILE_IMAGE_USER_ID` FOREIGN KEY (`USER_ID`) REFERENCES `US_USER` (`USER_ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='프로필 이미지 및 블라인드 표시 정보';

-- ---------------------------------------------------------------------
-- US_USER_PREFERENCE: 매칭 상대 선호 조건
-- ---------------------------------------------------------------------
CREATE TABLE `US_USER_PREFERENCE` (
    `USER_ID` BIGINT UNSIGNED NOT NULL COMMENT '사용자 ID',
    `PREFERRED_GENDER_CODE` VARCHAR(20) NULL COMMENT '선호 성별',
    `MIN_AGE` SMALLINT UNSIGNED NULL COMMENT '최소 연령',
    `MAX_AGE` SMALLINT UNSIGNED NULL COMMENT '최대 연령',
    `MIN_HEIGHT_CM` SMALLINT UNSIGNED NULL COMMENT '최소 키',
    `MAX_HEIGHT_CM` SMALLINT UNSIGNED NULL COMMENT '최대 키',
    `MAX_DISTANCE_KM` INT UNSIGNED NOT NULL DEFAULT 50 COMMENT '최대 거리',
    `PREFERRED_REGION_CODE` VARCHAR(20) NULL COMMENT '선호 지역',
    `PREFERRED_SMOKING_CODE` VARCHAR(20) NULL COMMENT '선호 흡연 조건',
    `PREFERRED_DRINKING_CODE` VARCHAR(20) NULL COMMENT '선호 음주 조건',
    `MATCHING_ENABLED_YN` CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '추천/매칭 참여 여부',
    `DELETED` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '논리 삭제 여부(Y/N)',
    `INSERT_USER` VARCHAR(50) NOT NULL COMMENT '최초 등록 사용자',
    `INSERT_DATE` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '최초 등록 일시',
    `UPDATE_USER` VARCHAR(50) NULL COMMENT '최종 수정 사용자',
    `UPDATE_DATE` DATETIME(6) NULL COMMENT '최종 수정 일시',
    `SYSTEM_REMARK` VARCHAR(1000) NULL COMMENT '시스템 처리 및 운영 메모',
    PRIMARY KEY (`USER_ID`),
    CONSTRAINT `FK_US_USER_PREFERENCE_USER_ID` FOREIGN KEY (`USER_ID`) REFERENCES `US_USER` (`USER_ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='매칭 상대 선호 조건';

-- ---------------------------------------------------------------------
-- US_INTEREST: 관심사 마스터
-- ---------------------------------------------------------------------
CREATE TABLE `US_INTEREST` (
    `INTEREST_ID` BIGINT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT '관심사 ID',
    `INTEREST_NAME` VARCHAR(100) NOT NULL COMMENT '관심사명',
    `CATEGORY_CODE` VARCHAR(50) NULL COMMENT '관심사 분류',
    `SORT_ORDER` INT NOT NULL DEFAULT 0 COMMENT '정렬 순서',
    `USE_YN` CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '사용 여부',
    `DELETED` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '논리 삭제 여부(Y/N)',
    `INSERT_USER` VARCHAR(50) NOT NULL COMMENT '최초 등록 사용자',
    `INSERT_DATE` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '최초 등록 일시',
    `UPDATE_USER` VARCHAR(50) NULL COMMENT '최종 수정 사용자',
    `UPDATE_DATE` DATETIME(6) NULL COMMENT '최종 수정 일시',
    `SYSTEM_REMARK` VARCHAR(1000) NULL COMMENT '시스템 처리 및 운영 메모',
    PRIMARY KEY (`INTEREST_ID`),
    CONSTRAINT `UK_US_INTEREST_NAME` UNIQUE (`INTEREST_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='관심사 마스터';

-- ---------------------------------------------------------------------
-- US_USER_INTEREST: 사용자 관심사 연결
-- ---------------------------------------------------------------------
CREATE TABLE `US_USER_INTEREST` (
    `USER_ID` BIGINT UNSIGNED NOT NULL COMMENT '사용자 ID',
    `INTEREST_ID` BIGINT UNSIGNED NOT NULL COMMENT '관심사 ID',
    `PRIORITY_ORDER` INT NOT NULL DEFAULT 0 COMMENT '사용자 관심 우선순위',
    `DELETED` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '논리 삭제 여부(Y/N)',
    `INSERT_USER` VARCHAR(50) NOT NULL COMMENT '최초 등록 사용자',
    `INSERT_DATE` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '최초 등록 일시',
    `UPDATE_USER` VARCHAR(50) NULL COMMENT '최종 수정 사용자',
    `UPDATE_DATE` DATETIME(6) NULL COMMENT '최종 수정 일시',
    `SYSTEM_REMARK` VARCHAR(1000) NULL COMMENT '시스템 처리 및 운영 메모',
    PRIMARY KEY (`USER_ID`, `INTEREST_ID`),
    CONSTRAINT `FK_US_USER_INTEREST_USER_ID` FOREIGN KEY (`USER_ID`) REFERENCES `US_USER` (`USER_ID`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT `FK_US_USER_INTEREST_INTEREST_ID` FOREIGN KEY (`INTEREST_ID`) REFERENCES `US_INTEREST` (`INTEREST_ID`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='사용자 관심사 연결';

-- ---------------------------------------------------------------------
-- US_USER_VERIFICATION: 본인·사진·직장 등 인증 심사
-- ---------------------------------------------------------------------
CREATE TABLE `US_USER_VERIFICATION` (
    `VERIFICATION_ID` BIGINT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT '인증 ID',
    `USER_ID` BIGINT UNSIGNED NOT NULL COMMENT '사용자 ID',
    `VERIFICATION_TYPE` VARCHAR(30) NOT NULL COMMENT 'IDENTITY/PHOTO/COMPANY/STUDENT',
    `VERIFICATION_VALUE_ENC` VARBINARY(1000) NULL COMMENT '인증값 암호화',
    `DOCUMENT_URL` VARCHAR(1000) NULL COMMENT '증빙 파일 URL',
    `VERIFICATION_STATUS` VARCHAR(20) NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING/APPROVED/REJECTED',
    `REJECT_REASON` VARCHAR(500) NULL COMMENT '반려 사유',
    `REVIEW_USER_ID` BIGINT UNSIGNED NULL COMMENT '심사 관리자 ID',
    `REVIEW_DATE` DATETIME(6) NULL COMMENT '심사 일시',
    `DELETED` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '논리 삭제 여부(Y/N)',
    `INSERT_USER` VARCHAR(50) NOT NULL COMMENT '최초 등록 사용자',
    `INSERT_DATE` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '최초 등록 일시',
    `UPDATE_USER` VARCHAR(50) NULL COMMENT '최종 수정 사용자',
    `UPDATE_DATE` DATETIME(6) NULL COMMENT '최종 수정 일시',
    `SYSTEM_REMARK` VARCHAR(1000) NULL COMMENT '시스템 처리 및 운영 메모',
    PRIMARY KEY (`VERIFICATION_ID`),
    INDEX `IX_US_VERIFICATION_USER` (`USER_ID`, `VERIFICATION_TYPE`, `DELETED`),
    INDEX `IX_US_VERIFICATION_STATUS` (`VERIFICATION_STATUS`, `DELETED`),
    CONSTRAINT `FK_US_USER_VERIFICATION_USER_ID` FOREIGN KEY (`USER_ID`) REFERENCES `US_USER` (`USER_ID`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT `FK_US_USER_VERIFICATION_REVIEW_USER_ID` FOREIGN KEY (`REVIEW_USER_ID`) REFERENCES `US_USER` (`USER_ID`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='본인·사진·직장 등 인증 심사';

-- ---------------------------------------------------------------------
-- ON_QUESTION: 온보딩 및 가치관 질문 마스터
-- ---------------------------------------------------------------------
CREATE TABLE `ON_QUESTION` (
    `QUESTION_ID` BIGINT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT '질문 ID',
    `QUESTION_TYPE` VARCHAR(20) NOT NULL DEFAULT 'SINGLE' COMMENT 'SINGLE/MULTI/TEXT/SCALE',
    `CATEGORY_CODE` VARCHAR(50) NOT NULL COMMENT '질문 분류',
    `QUESTION_TEXT` VARCHAR(500) NOT NULL COMMENT '질문 내용',
    `REQUIRED_YN` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '필수 여부',
    `MATCH_WEIGHT` DECIMAL(8,4) NOT NULL DEFAULT 1.0000 COMMENT '매칭 점수 가중치',
    `SORT_ORDER` INT NOT NULL DEFAULT 0 COMMENT '정렬 순서',
    `USE_YN` CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '사용 여부',
    `DELETED` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '논리 삭제 여부(Y/N)',
    `INSERT_USER` VARCHAR(50) NOT NULL COMMENT '최초 등록 사용자',
    `INSERT_DATE` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '최초 등록 일시',
    `UPDATE_USER` VARCHAR(50) NULL COMMENT '최종 수정 사용자',
    `UPDATE_DATE` DATETIME(6) NULL COMMENT '최종 수정 일시',
    `SYSTEM_REMARK` VARCHAR(1000) NULL COMMENT '시스템 처리 및 운영 메모',
    PRIMARY KEY (`QUESTION_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='온보딩 및 가치관 질문 마스터';

-- ---------------------------------------------------------------------
-- ON_QUESTION_OPTION: 선택형 질문의 보기
-- ---------------------------------------------------------------------
CREATE TABLE `ON_QUESTION_OPTION` (
    `OPTION_ID` BIGINT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT '보기 ID',
    `QUESTION_ID` BIGINT UNSIGNED NOT NULL COMMENT '질문 ID',
    `OPTION_CODE` VARCHAR(50) NOT NULL COMMENT '보기 코드',
    `OPTION_TEXT` VARCHAR(300) NOT NULL COMMENT '보기 내용',
    `SCORE_VALUE` DECIMAL(8,4) NULL COMMENT '알고리즘 계산용 값',
    `SORT_ORDER` INT NOT NULL DEFAULT 0 COMMENT '정렬 순서',
    `DELETED` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '논리 삭제 여부(Y/N)',
    `INSERT_USER` VARCHAR(50) NOT NULL COMMENT '최초 등록 사용자',
    `INSERT_DATE` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '최초 등록 일시',
    `UPDATE_USER` VARCHAR(50) NULL COMMENT '최종 수정 사용자',
    `UPDATE_DATE` DATETIME(6) NULL COMMENT '최종 수정 일시',
    `SYSTEM_REMARK` VARCHAR(1000) NULL COMMENT '시스템 처리 및 운영 메모',
    PRIMARY KEY (`OPTION_ID`),
    CONSTRAINT `UK_ON_OPTION_CODE` UNIQUE (`QUESTION_ID`, `OPTION_CODE`),
    CONSTRAINT `FK_ON_QUESTION_OPTION_QUESTION_ID` FOREIGN KEY (`QUESTION_ID`) REFERENCES `ON_QUESTION` (`QUESTION_ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='선택형 질문의 보기';

-- ---------------------------------------------------------------------
-- ON_USER_ANSWER: 사용자의 온보딩/가치관 답변
-- ---------------------------------------------------------------------
CREATE TABLE `ON_USER_ANSWER` (
    `ANSWER_ID` BIGINT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT '답변 ID',
    `USER_ID` BIGINT UNSIGNED NOT NULL COMMENT '사용자 ID',
    `QUESTION_ID` BIGINT UNSIGNED NOT NULL COMMENT '질문 ID',
    `OPTION_ID` BIGINT UNSIGNED NULL COMMENT '선택한 보기 ID',
    `ANSWER_TEXT` VARCHAR(2000) NULL COMMENT '주관식 답변',
    `ANSWER_NUMBER` DECIMAL(10,4) NULL COMMENT '척도/숫자형 답변',
    `DELETED` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '논리 삭제 여부(Y/N)',
    `INSERT_USER` VARCHAR(50) NOT NULL COMMENT '최초 등록 사용자',
    `INSERT_DATE` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '최초 등록 일시',
    `UPDATE_USER` VARCHAR(50) NULL COMMENT '최종 수정 사용자',
    `UPDATE_DATE` DATETIME(6) NULL COMMENT '최종 수정 일시',
    `SYSTEM_REMARK` VARCHAR(1000) NULL COMMENT '시스템 처리 및 운영 메모',
    PRIMARY KEY (`ANSWER_ID`),
    CONSTRAINT `UK_ON_USER_ANSWER` UNIQUE (`USER_ID`, `QUESTION_ID`, `OPTION_ID`),
    INDEX `IX_ON_USER_ANSWER_USER` (`USER_ID`, `DELETED`),
    CONSTRAINT `FK_ON_USER_ANSWER_USER_ID` FOREIGN KEY (`USER_ID`) REFERENCES `US_USER` (`USER_ID`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT `FK_ON_USER_ANSWER_QUESTION_ID` FOREIGN KEY (`QUESTION_ID`) REFERENCES `ON_QUESTION` (`QUESTION_ID`) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT `FK_ON_USER_ANSWER_OPTION_ID` FOREIGN KEY (`OPTION_ID`) REFERENCES `ON_QUESTION_OPTION` (`OPTION_ID`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='사용자의 온보딩/가치관 답변';

-- ---------------------------------------------------------------------
-- MT_MATCH_QUEUE: 블라인드 매칭 대기열
-- ---------------------------------------------------------------------
CREATE TABLE `MT_MATCH_QUEUE` (
    `QUEUE_ID` BIGINT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT '대기열 ID',
    `USER_ID` BIGINT UNSIGNED NOT NULL COMMENT '사용자 ID',
    `QUEUE_STATUS` VARCHAR(20) NOT NULL DEFAULT 'WAITING' COMMENT 'WAITING/PROCESSING/MATCHED/CANCELED/EXPIRED',
    `ENTER_DATE` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '대기열 진입 일시',
    `EXPIRE_DATE` DATETIME(6) NULL COMMENT '대기 만료 일시',
    `MATCHING_VERSION` VARCHAR(30) NOT NULL DEFAULT 'V1' COMMENT '알고리즘 버전',
    `DELETED` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '논리 삭제 여부(Y/N)',
    `INSERT_USER` VARCHAR(50) NOT NULL COMMENT '최초 등록 사용자',
    `INSERT_DATE` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '최초 등록 일시',
    `UPDATE_USER` VARCHAR(50) NULL COMMENT '최종 수정 사용자',
    `UPDATE_DATE` DATETIME(6) NULL COMMENT '최종 수정 일시',
    `SYSTEM_REMARK` VARCHAR(1000) NULL COMMENT '시스템 처리 및 운영 메모',
    PRIMARY KEY (`QUEUE_ID`),
    INDEX `IX_MT_QUEUE_STATUS` (`QUEUE_STATUS`, `ENTER_DATE`, `DELETED`),
    INDEX `IX_MT_QUEUE_USER` (`USER_ID`, `QUEUE_STATUS`, `DELETED`),
    CONSTRAINT `FK_MT_MATCH_QUEUE_USER_ID` FOREIGN KEY (`USER_ID`) REFERENCES `US_USER` (`USER_ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='블라인드 매칭 대기열';

-- ---------------------------------------------------------------------
-- MT_RECOMMENDATION_HISTORY: 추천 후보 노출 및 점수 이력
-- ---------------------------------------------------------------------
CREATE TABLE `MT_RECOMMENDATION_HISTORY` (
    `RECOMMENDATION_ID` BIGINT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT '추천 이력 ID',
    `USER_ID` BIGINT UNSIGNED NOT NULL COMMENT '추천을 받은 사용자',
    `TARGET_USER_ID` BIGINT UNSIGNED NOT NULL COMMENT '추천된 상대',
    `RECOMMENDATION_DATE` DATE NOT NULL COMMENT '추천 기준일',
    `MATCH_SCORE` DECIMAL(10,4) NULL COMMENT '종합 매칭 점수',
    `SCORE_DETAIL_JSON` JSON NULL COMMENT '점수 구성 상세',
    `EXPOSE_DATE` DATETIME(6) NULL COMMENT '화면 노출 일시',
    `CLICK_DATE` DATETIME(6) NULL COMMENT '상세 확인 일시',
    `ALGORITHM_VERSION` VARCHAR(30) NOT NULL DEFAULT 'V1' COMMENT '알고리즘 버전',
    `DELETED` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '논리 삭제 여부(Y/N)',
    `INSERT_USER` VARCHAR(50) NOT NULL COMMENT '최초 등록 사용자',
    `INSERT_DATE` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '최초 등록 일시',
    `UPDATE_USER` VARCHAR(50) NULL COMMENT '최종 수정 사용자',
    `UPDATE_DATE` DATETIME(6) NULL COMMENT '최종 수정 일시',
    `SYSTEM_REMARK` VARCHAR(1000) NULL COMMENT '시스템 처리 및 운영 메모',
    PRIMARY KEY (`RECOMMENDATION_ID`),
    CONSTRAINT `UK_MT_RECOMMENDATION_DAY` UNIQUE (`USER_ID`, `TARGET_USER_ID`, `RECOMMENDATION_DATE`),
    INDEX `IX_MT_RECOMMENDATION_USER` (`USER_ID`, `RECOMMENDATION_DATE`, `DELETED`),
    CONSTRAINT `FK_MT_RECOMMENDATION_HISTORY_USER_ID` FOREIGN KEY (`USER_ID`) REFERENCES `US_USER` (`USER_ID`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT `FK_MT_RECOMMENDATION_HISTORY_TARGET_USER_ID` FOREIGN KEY (`TARGET_USER_ID`) REFERENCES `US_USER` (`USER_ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='추천 후보 노출 및 점수 이력';

-- ---------------------------------------------------------------------
-- MT_USER_ACTION: 추천 상대에 대한 좋아요·패스
-- ---------------------------------------------------------------------
CREATE TABLE `MT_USER_ACTION` (
    `ACTION_ID` BIGINT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT '행동 ID',
    `FROM_USER_ID` BIGINT UNSIGNED NOT NULL COMMENT '행동 사용자',
    `TO_USER_ID` BIGINT UNSIGNED NOT NULL COMMENT '대상 사용자',
    `ACTION_TYPE` VARCHAR(20) NOT NULL COMMENT 'LIKE/SUPER_LIKE/PASS',
    `MESSAGE` VARCHAR(500) NULL COMMENT '호감 메시지',
    `ACTION_DATE` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '행동 일시',
    `DELETED` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '논리 삭제 여부(Y/N)',
    `INSERT_USER` VARCHAR(50) NOT NULL COMMENT '최초 등록 사용자',
    `INSERT_DATE` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '최초 등록 일시',
    `UPDATE_USER` VARCHAR(50) NULL COMMENT '최종 수정 사용자',
    `UPDATE_DATE` DATETIME(6) NULL COMMENT '최종 수정 일시',
    `SYSTEM_REMARK` VARCHAR(1000) NULL COMMENT '시스템 처리 및 운영 메모',
    PRIMARY KEY (`ACTION_ID`),
    CONSTRAINT `UK_MT_USER_ACTION` UNIQUE (`FROM_USER_ID`, `TO_USER_ID`),
    INDEX `IX_MT_USER_ACTION_TARGET` (`TO_USER_ID`, `ACTION_TYPE`, `DELETED`),
    CONSTRAINT `FK_MT_USER_ACTION_FROM_USER_ID` FOREIGN KEY (`FROM_USER_ID`) REFERENCES `US_USER` (`USER_ID`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT `FK_MT_USER_ACTION_TO_USER_ID` FOREIGN KEY (`TO_USER_ID`) REFERENCES `US_USER` (`USER_ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='추천 상대에 대한 좋아요·패스';

-- ---------------------------------------------------------------------
-- MT_MATCH: 상호 호감 또는 큐 기반으로 성사된 매칭
-- ---------------------------------------------------------------------
CREATE TABLE `MT_MATCH` (
    `MATCH_ID` BIGINT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT '매칭 ID',
    `USER1_ID` BIGINT UNSIGNED NOT NULL COMMENT '작은 사용자 ID',
    `USER2_ID` BIGINT UNSIGNED NOT NULL COMMENT '큰 사용자 ID',
    `MATCH_TYPE` VARCHAR(20) NOT NULL DEFAULT 'LIKE' COMMENT 'LIKE/QUEUE/MANUAL',
    `MATCH_STATUS` VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' COMMENT 'ACTIVE/UNMATCHED/BLOCKED/EXPIRED',
    `MATCH_SCORE` DECIMAL(10,4) NULL COMMENT '성사 시 매칭 점수',
    `MATCH_DATE` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '매칭 성사 일시',
    `END_DATE` DATETIME(6) NULL COMMENT '매칭 종료 일시',
    `END_USER_ID` BIGINT UNSIGNED NULL COMMENT '종료 처리 사용자',
    `END_REASON_CODE` VARCHAR(30) NULL COMMENT '종료 사유',
    `DELETED` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '논리 삭제 여부(Y/N)',
    `INSERT_USER` VARCHAR(50) NOT NULL COMMENT '최초 등록 사용자',
    `INSERT_DATE` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '최초 등록 일시',
    `UPDATE_USER` VARCHAR(50) NULL COMMENT '최종 수정 사용자',
    `UPDATE_DATE` DATETIME(6) NULL COMMENT '최종 수정 일시',
    `SYSTEM_REMARK` VARCHAR(1000) NULL COMMENT '시스템 처리 및 운영 메모',
    PRIMARY KEY (`MATCH_ID`),
    CONSTRAINT `UK_MT_MATCH_USERS` UNIQUE (`USER1_ID`, `USER2_ID`),
    INDEX `IX_MT_MATCH_USER1` (`USER1_ID`, `MATCH_STATUS`, `DELETED`),
    INDEX `IX_MT_MATCH_USER2` (`USER2_ID`, `MATCH_STATUS`, `DELETED`),
    CONSTRAINT `FK_MT_MATCH_USER1_ID` FOREIGN KEY (`USER1_ID`) REFERENCES `US_USER` (`USER_ID`) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT `FK_MT_MATCH_USER2_ID` FOREIGN KEY (`USER2_ID`) REFERENCES `US_USER` (`USER_ID`) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT `FK_MT_MATCH_END_USER_ID` FOREIGN KEY (`END_USER_ID`) REFERENCES `US_USER` (`USER_ID`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='상호 호감 또는 큐 기반으로 성사된 매칭';

-- ---------------------------------------------------------------------
-- CH_CHAT_ROOM: 매칭별 1:1 채팅방
-- ---------------------------------------------------------------------
CREATE TABLE `CH_CHAT_ROOM` (
    `CHAT_ROOM_ID` BIGINT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT '채팅방 ID',
    `MATCH_ID` BIGINT UNSIGNED NOT NULL COMMENT '매칭 ID',
    `ROOM_STATUS` VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' COMMENT 'ACTIVE/CLOSED',
    `LAST_MESSAGE_ID` BIGINT UNSIGNED NULL COMMENT '마지막 메시지 ID',
    `LAST_MESSAGE_DATE` DATETIME(6) NULL COMMENT '마지막 메시지 일시',
    `CLOSE_DATE` DATETIME(6) NULL COMMENT '채팅방 종료 일시',
    `DELETED` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '논리 삭제 여부(Y/N)',
    `INSERT_USER` VARCHAR(50) NOT NULL COMMENT '최초 등록 사용자',
    `INSERT_DATE` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '최초 등록 일시',
    `UPDATE_USER` VARCHAR(50) NULL COMMENT '최종 수정 사용자',
    `UPDATE_DATE` DATETIME(6) NULL COMMENT '최종 수정 일시',
    `SYSTEM_REMARK` VARCHAR(1000) NULL COMMENT '시스템 처리 및 운영 메모',
    PRIMARY KEY (`CHAT_ROOM_ID`),
    CONSTRAINT `UK_CH_CHAT_ROOM_MATCH` UNIQUE (`MATCH_ID`),
    INDEX `IX_CH_CHAT_ROOM_LAST` (`LAST_MESSAGE_DATE`, `DELETED`),
    CONSTRAINT `FK_CH_CHAT_ROOM_MATCH_ID` FOREIGN KEY (`MATCH_ID`) REFERENCES `MT_MATCH` (`MATCH_ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='매칭별 1:1 채팅방';

-- ---------------------------------------------------------------------
-- CH_CHAT_ROOM_MEMBER: 채팅방 참여자 및 읽음 위치
-- ---------------------------------------------------------------------
CREATE TABLE `CH_CHAT_ROOM_MEMBER` (
    `CHAT_ROOM_ID` BIGINT UNSIGNED NOT NULL COMMENT '채팅방 ID',
    `USER_ID` BIGINT UNSIGNED NOT NULL COMMENT '사용자 ID',
    `JOIN_DATE` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '입장 일시',
    `LEAVE_DATE` DATETIME(6) NULL COMMENT '퇴장 일시',
    `LAST_READ_MESSAGE_ID` BIGINT UNSIGNED NULL COMMENT '마지막 읽은 메시지',
    `NOTIFICATION_YN` CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '채팅 알림 여부',
    `DELETED` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '논리 삭제 여부(Y/N)',
    `INSERT_USER` VARCHAR(50) NOT NULL COMMENT '최초 등록 사용자',
    `INSERT_DATE` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '최초 등록 일시',
    `UPDATE_USER` VARCHAR(50) NULL COMMENT '최종 수정 사용자',
    `UPDATE_DATE` DATETIME(6) NULL COMMENT '최종 수정 일시',
    `SYSTEM_REMARK` VARCHAR(1000) NULL COMMENT '시스템 처리 및 운영 메모',
    PRIMARY KEY (`CHAT_ROOM_ID`, `USER_ID`),
    CONSTRAINT `FK_CH_CHAT_ROOM_MEMBER_CHAT_ROOM_ID` FOREIGN KEY (`CHAT_ROOM_ID`) REFERENCES `CH_CHAT_ROOM` (`CHAT_ROOM_ID`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT `FK_CH_CHAT_ROOM_MEMBER_USER_ID` FOREIGN KEY (`USER_ID`) REFERENCES `US_USER` (`USER_ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='채팅방 참여자 및 읽음 위치';

-- ---------------------------------------------------------------------
-- CH_CHAT_MESSAGE: WebSocket 실시간 채팅 메시지
-- ---------------------------------------------------------------------
CREATE TABLE `CH_CHAT_MESSAGE` (
    `MESSAGE_ID` BIGINT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT '메시지 ID',
    `CHAT_ROOM_ID` BIGINT UNSIGNED NOT NULL COMMENT '채팅방 ID',
    `SENDER_USER_ID` BIGINT UNSIGNED NOT NULL COMMENT '발신자 ID',
    `MESSAGE_TYPE` VARCHAR(20) NOT NULL DEFAULT 'TEXT' COMMENT 'TEXT/IMAGE/SYSTEM/REVEAL',
    `MESSAGE_CONTENT` TEXT NULL COMMENT '메시지 내용',
    `FILE_URL` VARCHAR(1000) NULL COMMENT '첨부 파일 URL',
    `REPLY_MESSAGE_ID` BIGINT UNSIGNED NULL COMMENT '답장 대상 메시지',
    `SEND_DATE` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '전송 일시',
    `DELETED` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '논리 삭제 여부(Y/N)',
    `INSERT_USER` VARCHAR(50) NOT NULL COMMENT '최초 등록 사용자',
    `INSERT_DATE` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '최초 등록 일시',
    `UPDATE_USER` VARCHAR(50) NULL COMMENT '최종 수정 사용자',
    `UPDATE_DATE` DATETIME(6) NULL COMMENT '최종 수정 일시',
    `SYSTEM_REMARK` VARCHAR(1000) NULL COMMENT '시스템 처리 및 운영 메모',
    PRIMARY KEY (`MESSAGE_ID`),
    INDEX `IX_CH_MESSAGE_ROOM` (`CHAT_ROOM_ID`, `MESSAGE_ID`, `DELETED`),
    INDEX `IX_CH_MESSAGE_SENDER` (`SENDER_USER_ID`, `SEND_DATE`, `DELETED`),
    CONSTRAINT `FK_CH_CHAT_MESSAGE_CHAT_ROOM_ID` FOREIGN KEY (`CHAT_ROOM_ID`) REFERENCES `CH_CHAT_ROOM` (`CHAT_ROOM_ID`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT `FK_CH_CHAT_MESSAGE_SENDER_USER_ID` FOREIGN KEY (`SENDER_USER_ID`) REFERENCES `US_USER` (`USER_ID`) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT `FK_CH_CHAT_MESSAGE_REPLY_MESSAGE_ID` FOREIGN KEY (`REPLY_MESSAGE_ID`) REFERENCES `CH_CHAT_MESSAGE` (`MESSAGE_ID`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='WebSocket 실시간 채팅 메시지';

-- ---------------------------------------------------------------------
-- RV_REVEAL_POLICY: 3단계 블라인드 해제 정책
-- ---------------------------------------------------------------------
CREATE TABLE `RV_REVEAL_POLICY` (
    `REVEAL_LEVEL` TINYINT UNSIGNED NOT NULL COMMENT '0 미공개, 1 실루엣/부분, 2 전체',
    `REVEAL_NAME` VARCHAR(100) NOT NULL COMMENT '단계명',
    `MIN_MESSAGE_COUNT` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '필요 메시지 수',
    `MIN_CHAT_MINUTES` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '필요 대화 시간',
    `MUTUAL_CONSENT_YN` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '상호 동의 필요 여부',
    `DISCLOSE_SCOPE_JSON` JSON NULL COMMENT '단계별 공개 항목',
    `USE_YN` CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '사용 여부',
    `DELETED` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '논리 삭제 여부(Y/N)',
    `INSERT_USER` VARCHAR(50) NOT NULL COMMENT '최초 등록 사용자',
    `INSERT_DATE` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '최초 등록 일시',
    `UPDATE_USER` VARCHAR(50) NULL COMMENT '최종 수정 사용자',
    `UPDATE_DATE` DATETIME(6) NULL COMMENT '최종 수정 일시',
    `SYSTEM_REMARK` VARCHAR(1000) NULL COMMENT '시스템 처리 및 운영 메모',
    PRIMARY KEY (`REVEAL_LEVEL`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='3단계 블라인드 해제 정책';

-- ---------------------------------------------------------------------
-- RV_REVEAL_PROGRESS: 매칭별 공개 단계 진행 상태
-- ---------------------------------------------------------------------
CREATE TABLE `RV_REVEAL_PROGRESS` (
    `MATCH_ID` BIGINT UNSIGNED NOT NULL COMMENT '매칭 ID',
    `CURRENT_LEVEL` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '현재 공개 단계',
    `MESSAGE_COUNT` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '누적 메시지 수',
    `CHAT_MINUTES` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '누적 대화 시간',
    `LAST_LEVEL_UP_DATE` DATETIME(6) NULL COMMENT '최근 단계 상승 일시',
    `FULL_REVEAL_DATE` DATETIME(6) NULL COMMENT '전체 공개 일시',
    `DELETED` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '논리 삭제 여부(Y/N)',
    `INSERT_USER` VARCHAR(50) NOT NULL COMMENT '최초 등록 사용자',
    `INSERT_DATE` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '최초 등록 일시',
    `UPDATE_USER` VARCHAR(50) NULL COMMENT '최종 수정 사용자',
    `UPDATE_DATE` DATETIME(6) NULL COMMENT '최종 수정 일시',
    `SYSTEM_REMARK` VARCHAR(1000) NULL COMMENT '시스템 처리 및 운영 메모',
    PRIMARY KEY (`MATCH_ID`),
    CONSTRAINT `FK_RV_REVEAL_PROGRESS_MATCH_ID` FOREIGN KEY (`MATCH_ID`) REFERENCES `MT_MATCH` (`MATCH_ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='매칭별 공개 단계 진행 상태';

-- ---------------------------------------------------------------------
-- RV_REVEAL_CONSENT: 매칭 참여자별 공개 단계 동의
-- ---------------------------------------------------------------------
CREATE TABLE `RV_REVEAL_CONSENT` (
    `MATCH_ID` BIGINT UNSIGNED NOT NULL COMMENT '매칭 ID',
    `USER_ID` BIGINT UNSIGNED NOT NULL COMMENT '사용자 ID',
    `REVEAL_LEVEL` TINYINT UNSIGNED NOT NULL COMMENT '동의 대상 단계',
    `CONSENT_STATUS` VARCHAR(20) NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING/ACCEPTED/REJECTED',
    `REQUEST_DATE` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '요청 일시',
    `RESPONSE_DATE` DATETIME(6) NULL COMMENT '응답 일시',
    `DELETED` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '논리 삭제 여부(Y/N)',
    `INSERT_USER` VARCHAR(50) NOT NULL COMMENT '최초 등록 사용자',
    `INSERT_DATE` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '최초 등록 일시',
    `UPDATE_USER` VARCHAR(50) NULL COMMENT '최종 수정 사용자',
    `UPDATE_DATE` DATETIME(6) NULL COMMENT '최종 수정 일시',
    `SYSTEM_REMARK` VARCHAR(1000) NULL COMMENT '시스템 처리 및 운영 메모',
    PRIMARY KEY (`MATCH_ID`, `USER_ID`, `REVEAL_LEVEL`),
    CONSTRAINT `FK_RV_REVEAL_CONSENT_MATCH_ID` FOREIGN KEY (`MATCH_ID`) REFERENCES `MT_MATCH` (`MATCH_ID`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT `FK_RV_REVEAL_CONSENT_USER_ID` FOREIGN KEY (`USER_ID`) REFERENCES `US_USER` (`USER_ID`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT `FK_RV_REVEAL_CONSENT_REVEAL_LEVEL` FOREIGN KEY (`REVEAL_LEVEL`) REFERENCES `RV_REVEAL_POLICY` (`REVEAL_LEVEL`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='매칭 참여자별 공개 단계 동의';

-- ---------------------------------------------------------------------
-- SF_USER_BLOCK: 사용자 차단
-- ---------------------------------------------------------------------
CREATE TABLE `SF_USER_BLOCK` (
    `BLOCK_USER_ID` BIGINT UNSIGNED NOT NULL COMMENT '차단한 사용자',
    `TARGET_USER_ID` BIGINT UNSIGNED NOT NULL COMMENT '차단된 사용자',
    `BLOCK_REASON` VARCHAR(500) NULL COMMENT '차단 사유',
    `BLOCK_DATE` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '차단 일시',
    `DELETED` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '논리 삭제 여부(Y/N)',
    `INSERT_USER` VARCHAR(50) NOT NULL COMMENT '최초 등록 사용자',
    `INSERT_DATE` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '최초 등록 일시',
    `UPDATE_USER` VARCHAR(50) NULL COMMENT '최종 수정 사용자',
    `UPDATE_DATE` DATETIME(6) NULL COMMENT '최종 수정 일시',
    `SYSTEM_REMARK` VARCHAR(1000) NULL COMMENT '시스템 처리 및 운영 메모',
    PRIMARY KEY (`BLOCK_USER_ID`, `TARGET_USER_ID`),
    CONSTRAINT `FK_SF_USER_BLOCK_BLOCK_USER_ID` FOREIGN KEY (`BLOCK_USER_ID`) REFERENCES `US_USER` (`USER_ID`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT `FK_SF_USER_BLOCK_TARGET_USER_ID` FOREIGN KEY (`TARGET_USER_ID`) REFERENCES `US_USER` (`USER_ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='사용자 차단';

-- ---------------------------------------------------------------------
-- SF_USER_REPORT: 사용자 및 채팅 신고
-- ---------------------------------------------------------------------
CREATE TABLE `SF_USER_REPORT` (
    `REPORT_ID` BIGINT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT '신고 ID',
    `REPORT_USER_ID` BIGINT UNSIGNED NOT NULL COMMENT '신고자',
    `TARGET_USER_ID` BIGINT UNSIGNED NOT NULL COMMENT '피신고자',
    `MATCH_ID` BIGINT UNSIGNED NULL COMMENT '관련 매칭 ID',
    `MESSAGE_ID` BIGINT UNSIGNED NULL COMMENT '관련 메시지 ID',
    `REPORT_TYPE` VARCHAR(30) NOT NULL COMMENT 'ABUSE/FAKE/FRAUD/SEXUAL/ETC',
    `REPORT_CONTENT` VARCHAR(2000) NULL COMMENT '상세 신고 내용',
    `REPORT_STATUS` VARCHAR(20) NOT NULL DEFAULT 'RECEIVED' COMMENT 'RECEIVED/REVIEWING/RESOLVED/REJECTED',
    `ACTION_CODE` VARCHAR(30) NULL COMMENT 'WARNING/RESTRICT/SUSPEND/BAN',
    `PROCESS_USER_ID` BIGINT UNSIGNED NULL COMMENT '처리 관리자',
    `PROCESS_DATE` DATETIME(6) NULL COMMENT '처리 일시',
    `DELETED` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '논리 삭제 여부(Y/N)',
    `INSERT_USER` VARCHAR(50) NOT NULL COMMENT '최초 등록 사용자',
    `INSERT_DATE` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '최초 등록 일시',
    `UPDATE_USER` VARCHAR(50) NULL COMMENT '최종 수정 사용자',
    `UPDATE_DATE` DATETIME(6) NULL COMMENT '최종 수정 일시',
    `SYSTEM_REMARK` VARCHAR(1000) NULL COMMENT '시스템 처리 및 운영 메모',
    PRIMARY KEY (`REPORT_ID`),
    INDEX `IX_SF_REPORT_TARGET` (`TARGET_USER_ID`, `REPORT_STATUS`, `DELETED`),
    INDEX `IX_SF_REPORT_STATUS` (`REPORT_STATUS`, `INSERT_DATE`, `DELETED`),
    CONSTRAINT `FK_SF_USER_REPORT_REPORT_USER_ID` FOREIGN KEY (`REPORT_USER_ID`) REFERENCES `US_USER` (`USER_ID`) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT `FK_SF_USER_REPORT_TARGET_USER_ID` FOREIGN KEY (`TARGET_USER_ID`) REFERENCES `US_USER` (`USER_ID`) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT `FK_SF_USER_REPORT_MATCH_ID` FOREIGN KEY (`MATCH_ID`) REFERENCES `MT_MATCH` (`MATCH_ID`) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT `FK_SF_USER_REPORT_MESSAGE_ID` FOREIGN KEY (`MESSAGE_ID`) REFERENCES `CH_CHAT_MESSAGE` (`MESSAGE_ID`) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT `FK_SF_USER_REPORT_PROCESS_USER_ID` FOREIGN KEY (`PROCESS_USER_ID`) REFERENCES `US_USER` (`USER_ID`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='사용자 및 채팅 신고';

-- ---------------------------------------------------------------------
-- SF_USER_SANCTION: 신고 누적에 따른 제재 이력
-- ---------------------------------------------------------------------
CREATE TABLE `SF_USER_SANCTION` (
    `SANCTION_ID` BIGINT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT '제재 ID',
    `USER_ID` BIGINT UNSIGNED NOT NULL COMMENT '제재 대상 사용자',
    `SANCTION_TYPE` VARCHAR(30) NOT NULL COMMENT 'WARNING/CHAT_LIMIT/MATCH_LIMIT/SUSPEND/BAN',
    `START_DATE` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '제재 시작',
    `END_DATE` DATETIME(6) NULL COMMENT '제재 종료',
    `REASON` VARCHAR(1000) NOT NULL COMMENT '제재 사유',
    `SOURCE_REPORT_ID` BIGINT UNSIGNED NULL COMMENT '근거 신고',
    `ACTIVE_YN` CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '활성 여부',
    `DELETED` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '논리 삭제 여부(Y/N)',
    `INSERT_USER` VARCHAR(50) NOT NULL COMMENT '최초 등록 사용자',
    `INSERT_DATE` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '최초 등록 일시',
    `UPDATE_USER` VARCHAR(50) NULL COMMENT '최종 수정 사용자',
    `UPDATE_DATE` DATETIME(6) NULL COMMENT '최종 수정 일시',
    `SYSTEM_REMARK` VARCHAR(1000) NULL COMMENT '시스템 처리 및 운영 메모',
    PRIMARY KEY (`SANCTION_ID`),
    INDEX `IX_SF_SANCTION_USER` (`USER_ID`, `ACTIVE_YN`, `DELETED`),
    CONSTRAINT `FK_SF_USER_SANCTION_USER_ID` FOREIGN KEY (`USER_ID`) REFERENCES `US_USER` (`USER_ID`) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT `FK_SF_USER_SANCTION_SOURCE_REPORT_ID` FOREIGN KEY (`SOURCE_REPORT_ID`) REFERENCES `SF_USER_REPORT` (`REPORT_ID`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='신고 누적에 따른 제재 이력';

-- ---------------------------------------------------------------------
-- NT_NOTIFICATION: 인앱 알림
-- ---------------------------------------------------------------------
CREATE TABLE `NT_NOTIFICATION` (
    `NOTIFICATION_ID` BIGINT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT '알림 ID',
    `USER_ID` BIGINT UNSIGNED NOT NULL COMMENT '수신 사용자',
    `NOTIFICATION_TYPE` VARCHAR(30) NOT NULL COMMENT 'MATCH/MESSAGE/REVEAL/REPORT/SYSTEM',
    `TITLE` VARCHAR(200) NOT NULL COMMENT '알림 제목',
    `CONTENT` VARCHAR(1000) NULL COMMENT '알림 내용',
    `REFERENCE_TYPE` VARCHAR(30) NULL COMMENT '참조 엔티티 유형',
    `REFERENCE_ID` BIGINT UNSIGNED NULL COMMENT '참조 엔티티 ID',
    `READ_YN` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '읽음 여부',
    `READ_DATE` DATETIME(6) NULL COMMENT '읽은 일시',
    `DELETED` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '논리 삭제 여부(Y/N)',
    `INSERT_USER` VARCHAR(50) NOT NULL COMMENT '최초 등록 사용자',
    `INSERT_DATE` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '최초 등록 일시',
    `UPDATE_USER` VARCHAR(50) NULL COMMENT '최종 수정 사용자',
    `UPDATE_DATE` DATETIME(6) NULL COMMENT '최종 수정 일시',
    `SYSTEM_REMARK` VARCHAR(1000) NULL COMMENT '시스템 처리 및 운영 메모',
    PRIMARY KEY (`NOTIFICATION_ID`),
    INDEX `IX_NT_NOTIFICATION_USER` (`USER_ID`, `READ_YN`, `INSERT_DATE`, `DELETED`),
    CONSTRAINT `FK_NT_NOTIFICATION_USER_ID` FOREIGN KEY (`USER_ID`) REFERENCES `US_USER` (`USER_ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='인앱 알림';

-- ---------------------------------------------------------------------
-- SY_TERMS: 서비스 약관 버전 관리
-- ---------------------------------------------------------------------
CREATE TABLE `SY_TERMS` (
    `TERMS_ID` BIGINT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT '약관 ID',
    `TERMS_TYPE` VARCHAR(30) NOT NULL COMMENT 'SERVICE/PRIVACY/LOCATION/MARKETING',
    `VERSION` VARCHAR(20) NOT NULL COMMENT '약관 버전',
    `TITLE` VARCHAR(200) NOT NULL COMMENT '약관 제목',
    `CONTENT` LONGTEXT NOT NULL COMMENT '약관 본문',
    `REQUIRED_YN` CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '필수 여부',
    `EFFECTIVE_DATE` DATETIME(6) NOT NULL COMMENT '시행 일시',
    `USE_YN` CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '사용 여부',
    `DELETED` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '논리 삭제 여부(Y/N)',
    `INSERT_USER` VARCHAR(50) NOT NULL COMMENT '최초 등록 사용자',
    `INSERT_DATE` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '최초 등록 일시',
    `UPDATE_USER` VARCHAR(50) NULL COMMENT '최종 수정 사용자',
    `UPDATE_DATE` DATETIME(6) NULL COMMENT '최종 수정 일시',
    `SYSTEM_REMARK` VARCHAR(1000) NULL COMMENT '시스템 처리 및 운영 메모',
    PRIMARY KEY (`TERMS_ID`),
    CONSTRAINT `UK_SY_TERMS_VERSION` UNIQUE (`TERMS_TYPE`, `VERSION`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='서비스 약관 버전 관리';

-- ---------------------------------------------------------------------
-- SY_USER_AGREEMENT: 사용자 약관 동의 이력
-- ---------------------------------------------------------------------
CREATE TABLE `SY_USER_AGREEMENT` (
    `AGREEMENT_ID` BIGINT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT '동의 ID',
    `USER_ID` BIGINT UNSIGNED NOT NULL COMMENT '사용자 ID',
    `TERMS_ID` BIGINT UNSIGNED NOT NULL COMMENT '약관 ID',
    `AGREED_YN` CHAR(1) NOT NULL COMMENT '동의 여부',
    `AGREEMENT_DATE` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '동의 일시',
    `CLIENT_IP` VARCHAR(45) NULL COMMENT '접속 IP',
    `DELETED` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '논리 삭제 여부(Y/N)',
    `INSERT_USER` VARCHAR(50) NOT NULL COMMENT '최초 등록 사용자',
    `INSERT_DATE` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '최초 등록 일시',
    `UPDATE_USER` VARCHAR(50) NULL COMMENT '최종 수정 사용자',
    `UPDATE_DATE` DATETIME(6) NULL COMMENT '최종 수정 일시',
    `SYSTEM_REMARK` VARCHAR(1000) NULL COMMENT '시스템 처리 및 운영 메모',
    PRIMARY KEY (`AGREEMENT_ID`),
    CONSTRAINT `UK_SY_USER_AGREEMENT` UNIQUE (`USER_ID`, `TERMS_ID`),
    CONSTRAINT `FK_SY_USER_AGREEMENT_USER_ID` FOREIGN KEY (`USER_ID`) REFERENCES `US_USER` (`USER_ID`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT `FK_SY_USER_AGREEMENT_TERMS_ID` FOREIGN KEY (`TERMS_ID`) REFERENCES `SY_TERMS` (`TERMS_ID`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='사용자 약관 동의 이력';

-- ---------------------------------------------------------------------
-- PY_PRODUCT: 부가 기능 상품
-- ---------------------------------------------------------------------
CREATE TABLE `PY_PRODUCT` (
    `PRODUCT_ID` BIGINT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT '상품 ID',
    `PRODUCT_CODE` VARCHAR(50) NOT NULL COMMENT '상품 코드',
    `PRODUCT_NAME` VARCHAR(200) NOT NULL COMMENT '상품명',
    `PRODUCT_TYPE` VARCHAR(30) NOT NULL COMMENT 'SUBSCRIPTION/ITEM',
    `PRICE` DECIMAL(12,2) NOT NULL COMMENT '판매 가격',
    `CURRENCY_CODE` CHAR(3) NOT NULL DEFAULT 'KRW' COMMENT '통화',
    `BENEFIT_JSON` JSON NULL COMMENT '혜택 구성',
    `USE_YN` CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '사용 여부',
    `DELETED` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '논리 삭제 여부(Y/N)',
    `INSERT_USER` VARCHAR(50) NOT NULL COMMENT '최초 등록 사용자',
    `INSERT_DATE` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '최초 등록 일시',
    `UPDATE_USER` VARCHAR(50) NULL COMMENT '최종 수정 사용자',
    `UPDATE_DATE` DATETIME(6) NULL COMMENT '최종 수정 일시',
    `SYSTEM_REMARK` VARCHAR(1000) NULL COMMENT '시스템 처리 및 운영 메모',
    PRIMARY KEY (`PRODUCT_ID`),
    CONSTRAINT `UK_PY_PRODUCT_CODE` UNIQUE (`PRODUCT_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='부가 기능 상품';

-- ---------------------------------------------------------------------
-- PY_PAYMENT: 토스페이먼츠 결제 원장
-- ---------------------------------------------------------------------
CREATE TABLE `PY_PAYMENT` (
    `PAYMENT_ID` BIGINT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT '내부 결제 ID',
    `USER_ID` BIGINT UNSIGNED NOT NULL COMMENT '사용자 ID',
    `PRODUCT_ID` BIGINT UNSIGNED NOT NULL COMMENT '상품 ID',
    `ORDER_ID` VARCHAR(100) NOT NULL COMMENT '토스 주문 ID',
    `PAYMENT_KEY` VARCHAR(200) NULL COMMENT '토스 결제 키',
    `BILLING_KEY_ENC` VARBINARY(1000) NULL COMMENT '빌링키 암호화',
    `PAYMENT_STATUS` VARCHAR(30) NOT NULL DEFAULT 'READY' COMMENT 'READY/DONE/CANCELED/FAILED',
    `AMOUNT` DECIMAL(12,2) NOT NULL COMMENT '결제 금액',
    `CURRENCY_CODE` CHAR(3) NOT NULL DEFAULT 'KRW' COMMENT '통화',
    `APPROVED_DATE` DATETIME(6) NULL COMMENT '승인 일시',
    `CANCELED_DATE` DATETIME(6) NULL COMMENT '취소 일시',
    `FAIL_CODE` VARCHAR(100) NULL COMMENT '실패 코드',
    `FAIL_MESSAGE` VARCHAR(1000) NULL COMMENT '실패 메시지',
    `DELETED` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '논리 삭제 여부(Y/N)',
    `INSERT_USER` VARCHAR(50) NOT NULL COMMENT '최초 등록 사용자',
    `INSERT_DATE` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '최초 등록 일시',
    `UPDATE_USER` VARCHAR(50) NULL COMMENT '최종 수정 사용자',
    `UPDATE_DATE` DATETIME(6) NULL COMMENT '최종 수정 일시',
    `SYSTEM_REMARK` VARCHAR(1000) NULL COMMENT '시스템 처리 및 운영 메모',
    PRIMARY KEY (`PAYMENT_ID`),
    CONSTRAINT `UK_PY_PAYMENT_ORDER` UNIQUE (`ORDER_ID`),
    CONSTRAINT `UK_PY_PAYMENT_KEY` UNIQUE (`PAYMENT_KEY`),
    INDEX `IX_PY_PAYMENT_USER` (`USER_ID`, `INSERT_DATE`, `DELETED`),
    INDEX `IX_PY_PAYMENT_STATUS` (`PAYMENT_STATUS`, `INSERT_DATE`, `DELETED`),
    CONSTRAINT `FK_PY_PAYMENT_USER_ID` FOREIGN KEY (`USER_ID`) REFERENCES `US_USER` (`USER_ID`) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT `FK_PY_PAYMENT_PRODUCT_ID` FOREIGN KEY (`PRODUCT_ID`) REFERENCES `PY_PRODUCT` (`PRODUCT_ID`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='토스페이먼츠 결제 원장';

-- ---------------------------------------------------------------------
-- PY_PAYMENT_EVENT: 결제 승인·취소·웹훅 이벤트 원문
-- ---------------------------------------------------------------------
CREATE TABLE `PY_PAYMENT_EVENT` (
    `EVENT_ID` BIGINT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT '이벤트 ID',
    `PAYMENT_ID` BIGINT UNSIGNED NULL COMMENT '내부 결제 ID',
    `EVENT_TYPE` VARCHAR(50) NOT NULL COMMENT 'REQUEST/APPROVE/CANCEL/WEBHOOK',
    `EVENT_STATUS` VARCHAR(20) NOT NULL COMMENT 'SUCCESS/FAIL',
    `IDEMPOTENCY_KEY` VARCHAR(100) NULL COMMENT '멱등성 키',
    `REQUEST_JSON` JSON NULL COMMENT '요청 본문',
    `RESPONSE_JSON` JSON NULL COMMENT '응답/웹훅 본문',
    `ERROR_MESSAGE` VARCHAR(2000) NULL COMMENT '오류 메시지',
    `DELETED` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '논리 삭제 여부(Y/N)',
    `INSERT_USER` VARCHAR(50) NOT NULL COMMENT '최초 등록 사용자',
    `INSERT_DATE` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '최초 등록 일시',
    `UPDATE_USER` VARCHAR(50) NULL COMMENT '최종 수정 사용자',
    `UPDATE_DATE` DATETIME(6) NULL COMMENT '최종 수정 일시',
    `SYSTEM_REMARK` VARCHAR(1000) NULL COMMENT '시스템 처리 및 운영 메모',
    PRIMARY KEY (`EVENT_ID`),
    CONSTRAINT `UK_PY_PAYMENT_EVENT_IDEMPOTENCY` UNIQUE (`IDEMPOTENCY_KEY`),
    INDEX `IX_PY_PAYMENT_EVENT_PAYMENT` (`PAYMENT_ID`, `INSERT_DATE`, `DELETED`),
    CONSTRAINT `FK_PY_PAYMENT_EVENT_PAYMENT_ID` FOREIGN KEY (`PAYMENT_ID`) REFERENCES `PY_PAYMENT` (`PAYMENT_ID`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='결제 승인·취소·웹훅 이벤트 원문';

-- 비즈니스 무결성 CHECK 제약
ALTER TABLE `US_USER_PROFILE`
    ADD CONSTRAINT `CK_US_PROFILE_HEIGHT` CHECK (`HEIGHT_CM` IS NULL OR `HEIGHT_CM` BETWEEN 100 AND 250);

ALTER TABLE `US_USER_PREFERENCE`
    ADD CONSTRAINT `CK_US_PREF_AGE` CHECK (`MIN_AGE` IS NULL OR `MAX_AGE` IS NULL OR `MIN_AGE` <= `MAX_AGE`),
    ADD CONSTRAINT `CK_US_PREF_HEIGHT` CHECK (`MIN_HEIGHT_CM` IS NULL OR `MAX_HEIGHT_CM` IS NULL OR `MIN_HEIGHT_CM` <= `MAX_HEIGHT_CM`);

-- ALTER TABLE `MT_USER_ACTION`
    -- ADD CONSTRAINT `CK_MT_ACTION_SELF` CHECK (`FROM_USER_ID` <> `TO_USER_ID`);

-- ALTER TABLE `MT_MATCH`
    -- ADD CONSTRAINT `CK_MT_MATCH_USER_ORDER` CHECK (`USER1_ID` < `USER2_ID`);

-- ALTER TABLE `SF_USER_BLOCK`
    -- ADD CONSTRAINT `CK_SF_BLOCK_SELF` CHECK (`BLOCK_USER_ID` <> `TARGET_USER_ID`);

-- 순환 참조 방지를 위해 테이블 생성 후 FK 추가
ALTER TABLE `CH_CHAT_ROOM`
    ADD CONSTRAINT `FK_CH_CHAT_ROOM_LAST_MESSAGE` FOREIGN KEY (`LAST_MESSAGE_ID`)
    REFERENCES `CH_CHAT_MESSAGE` (`MESSAGE_ID`) ON DELETE SET NULL ON UPDATE CASCADE;

SET FOREIGN_KEY_CHECKS = 1;

-- 운영 권장 규칙
-- 1) 일반 조회는 항상 DELETED='N' 조건 적용
-- 2) 수정 시 UPDATE_USER, UPDATE_DATE=CURRENT_TIMESTAMP(6) 반영
-- 3) 회원 탈퇴는 USER_STATUS='WITHDRAWN', WITHDRAW_DATE 기록 후 개인정보 익명화
-- 4) MT_MATCH 저장 시 USER1_ID < USER2_ID 순서를 애플리케이션에서 보장
--    (Match.between() 이 항상 작은 ID 를 USER1_ID 에 넣어 이 규칙을 지킨다)
-- 5) MT_USER_ACTION, ON_USER_ANSWER, SF_USER_BLOCK 등 유니크 제약이 걸린 테이블은
--    재삽입 대신 기존 행을 조회해 갱신한다(각 서비스 주석 참고)
