-- =====================================================================
-- V3: US_PROFILE_IMAGE 를 공개 URL 방식에서 저장소 오브젝트 키 방식으로 변경
--
-- 원본 backend/database/V1_1__profile_image_object_key.sql 을 옮긴 것이다.
-- USE `bma`; 는 제거했다(V1 헤더 주석 참고).
-- =====================================================================

ALTER TABLE US_PROFILE_IMAGE
    DROP COLUMN ORIGINAL_URL,
    DROP COLUMN BLURRED_URL,
    DROP COLUMN SILHOUETTE_URL,
    DROP COLUMN IMAGE_TYPE,
    -- 로컬 저장소 구현이 기본이므로 기본값을 LOCAL 로 둔다(S3 도입 시 변경).
    ADD COLUMN STORAGE_TYPE VARCHAR(20) NOT NULL DEFAULT 'LOCAL' AFTER USER_ID,
    ADD COLUMN ORIGINAL_OBJECT_KEY VARCHAR(500) NOT NULL AFTER STORAGE_TYPE,
    -- 블러/실루엣 이미지는 후처리로 생성되므로 처음에는 NULL 이다.
    -- ProfileMaskingService 는 해당 단계의 키가 없으면 그 이미지를 목록에서 제외한다.
    ADD COLUMN BLURRED_OBJECT_KEY VARCHAR(500) NULL AFTER ORIGINAL_OBJECT_KEY,
    ADD COLUMN SILHOUETTE_OBJECT_KEY VARCHAR(500) NULL AFTER BLURRED_OBJECT_KEY,
    ADD COLUMN ORIGINAL_FILE_NAME VARCHAR(255) NULL AFTER SILHOUETTE_OBJECT_KEY,
    ADD COLUMN CONTENT_TYPE VARCHAR(100) NULL AFTER ORIGINAL_FILE_NAME,
    ADD COLUMN FILE_SIZE BIGINT UNSIGNED NULL AFTER CONTENT_TYPE,
    ADD COLUMN FILE_HASH VARCHAR(64) NULL AFTER FILE_SIZE,
    ADD COLUMN IMAGE_WIDTH INT UNSIGNED NULL AFTER FILE_HASH,
    ADD COLUMN IMAGE_HEIGHT INT UNSIGNED NULL AFTER IMAGE_WIDTH;
